# Generated by Django 4.0.4 on 2022-05-27 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=700)),
                ('image_file', models.FileField(upload_to='photos/static/uploads/')),
                ('dated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
