# Generated by Django 4.0.4 on 2022-05-27 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ('-dated',), 'verbose_name_plural': 'images'},
        ),
    ]
