# Generated by Django 4.0.4 on 2022-05-27 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0006_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
    ]
